# Generated by SnowIaC for ticket RITM0654928
# Requested for: Amy, smith
# Description: We are in process of migrating oracle to SQL Server , orac1 to new VMs:   sql1.    We are facing performance issue due to Premium V2 supports 3000 IOPS and 125 mbps only.   Please increase the through

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "resource_group_name" {
  type        = string
  description = "Resource group containing the data disk for VM sql1"
}

variable "disk_name" {
  type        = string
  description = "Managed disk name attached to sql1"
}

# Update the Premium V2 disk performance tier per ticket RITM0654928
resource "azurerm_managed_disk" "sql1_data" {
  name                 = var.disk_name
  resource_group_name  = var.resource_group_name
  location             = "eastus2"
  storage_account_type = "PremiumV2_LRS"
  create_option        = "Empty"
  disk_size_gb         = 1024

  disk_iops_read_write     = 5000
  disk_mbps_read_write     = 125

  tags = {
    snow_ticket = "RITM0654928"
    managed_by  = "snowiac"
  }

  lifecycle {
    ignore_changes = [disk_size_gb, create_option]
  }
}

output "disk_iops" {
  value = azurerm_managed_disk.sql1_data.disk_iops_read_write
}

output "disk_mbps" {
  value = azurerm_managed_disk.sql1_data.disk_mbps_read_write
}
